name: MLflow Project Training CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MLflow & Dependencies
        run: pip install mlflow dagshub pandas scikit-learn matplotlib seaborn virtualenv

      - name: Train Model with MLflow
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.TOKEN }} 
          DAGSHUB_USER_TOKEN: ${{ secrets.TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/nasikhunamin815/Workflow-CI.mlflow
        run: |
          mlflow run MLProject --env-manager=local --experiment-name Mushroom_Classification_CI
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.TOKEN }}
          DAGSHUB_USER_TOKEN: ${{ secrets.TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/nasikhunamin815/Workflow-CI.mlflow
        run: |
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/mushroom-model:latest"
          
          echo "Building Docker Image: $IMAGE_TAG from latest registered model..."
          
          mlflow models build-docker \
            --model-uri "models:/Mushroom_Model/Latest" \
            --name "$IMAGE_TAG" \
            --enable-mlserver
          
          echo "Pushing image to Docker Hub..."
          docker push "$IMAGE_TAG"
